### ISSUE TITLE
What happens when a nav action fails

### ISSUE THREAD

**Issue by hawesie** [bfalacerda/strands_executive#12]
Our conversation earlier made me want to double-check what happens when a nav action fatally fails, e.g. when a door wait times out. Is it that the action server returns aborted with some actions remaining unexecuted?

**Comment by bfalacerda** [comment]
No, it returns successful because there was no error per se. Looking at the feedback you can figure out which tasks weren't executed

**Comment by hawesie** [comment]
Ok, thanks.
