### ISSUE TITLE
Expected time for a navigation task

### ISSUE THREAD

**Issue by hawesie** [bfalacerda/strands_executive#6]
In the new framework, how do I use the `get_guarantees_for_co_safe_task` service to get the expected time for a _navigation_ task? And am I right to assume that the expected time is agnostic of starting point?

**Comment by hawesie** [comment]
Also, does `travel_times` now refer to total expected execution time? (as this is not just travel)

I get the "starting point" now looking at the service.

**Comment by bfalacerda** [comment]
you can give it a spec, and just fill the ltl_task to be `'F "WayPointx"'` (note the "", they are needed)

The outcome is still expected times for each possible initial waypoint, same as the old service. You're right about `travel_times`, just forgot to change it while copy/pasting. I'll change it to `expected_times`

**Comment by bfalacerda** [comment]
also note that calculating for all possible waypoints can be super expensive when we are also modelling doors, so we might need to have a service that also receives the initial waypoint as input, along with a service that gives the probability distributions over waypoints of finishing the current task there.

We should be able to survive with this for now. Are you testing on the TSC topo map, with door passes?

**Comment by hawesie** [comment]
I'm testing on the tsc topological map, but with dummy nav. The topological map contains doorPassing edges. Is that the right type?

**Comment by bfalacerda** [comment]
door_wait_and_pass

**Comment by hawesie** [comment]
Ok, I'll update the file.

**Comment by bfalacerda** [comment]
cool- you'll need this: https://github.com/strands-project/strands_apps/pull/44

**Comment by hawesie** [comment]
I'm not actually running a simulated robot, just something that appears to be one, so I don't need that yet.

**Comment by bfalacerda** [comment]
with this the robot executes the `door_waiting` action before transversing door edges. The MDP is configured to assume the most probable outcome when unexpected things happen, but I don't know if it'll work. I think it can handle missing action servers and continue without crashing (assuming open doors), if not let me know
